# reproducibility
seed: 42

# model name
model_name: bert-dmlm-6l-512hs-8h-fp16

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  accumulate_grad_batches: 4
  gradient_clip_val: 10.0
  val_check_interval: 1.0
  max_steps: 1_000_000
  precision: 16
  num_sanity_val_steps: 0

monitor_metric: val_loss/dataloader_idx_0

# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ${train.monitor_metric}
  mode: min
  patience: 50

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${train.monitor_metric}
  mode: min
  verbose: True
  save_top_k: 2
  dirpath: experiments/${train.model_name}
